### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by mcf20** [ucd-plse/FPLearner#1]
Hello, I would like to ask how to run without pulling an image using Docker, directly within the PyCharm terminal instead.

**Comment by RainyTong** [comment]
> Hello, I would like to ask how to run without pulling an image using Docker, directly within the PyCharm terminal instead.

Hi, though using docker is highly recommended, it is possible to run without using docker. It is highly recommended to install the following requirements to setup the environment:

- LLVM version 12.0.1
- Joern installed from [https://github.com/joernio/joern/releases/download/v1.1.922/joern-install.sh](https://github.com/joernio/joern/releases/download/v1.1.922/joern-install.sh) 
- Python libraries:
```
numpy
pandas
tqdm
torch==1.13.0+cu117 
torchvision==0.14.0+cu117
torchaudio==0.13.0
pyg_lib
torch_scatter 
torch_sparse 
torch_cluster 
torch_spline_conv 
torch_geometric
torchtext==0.14.1
matplotlib==3.7.1
nltk==3.8.1
```
